### ISSUE TITLE
no such file or directory, expand-region-core

### ISSUE THREAD

**Issue by jhegedus42** [ensime/ensime.github.io#101]
Compiling file /home/joco/.emacs.d/elpa/ensime-20160328.644/ensime-expand-region.el at Wed Mar 30 16:24:13 2016
ensime-expand-region.el:22:1:Error: Cannot open load file: no such file or directory, expand-region-core

Any idea what might be going wrong ?

**Comment by fommil** [comment]
Can you please follow the steps at http://ensime.org/getting_help

**Comment by jhegedus42** [comment]
ok, sorry.

**Comment by fommil** [comment]
FYI it is a harmless message :wink: but glad you found the docs.
