### ISSUE TITLE
button to select alternative layouts

### ISSUE THREAD

**Issue by alphapapa** [ensime/ensime.github.io#102]
The ENSIME web site currently uses an extreme amount of padding, margins, and enormous navigation areas, resulting in a tiny space for actual content to be displayed.

A common setup is to have a 1080p monitor divided in half, with an editor on one half and a browser on the other (window managers and even Windows makes this easy).  When used in this setup, the width of the content area is about 380 pixels, while the width of the navigation area is about 570 pixels.  Additionally, the content area has about 200 pixels of margin and padding, leaving about **180 pixels** of horizontal space to display the actual documentation, only **19%** of the browser window's width.

![ensime1](https://cloud.githubusercontent.com/assets/601365/14214605/9b8b3c82-f803-11e5-8952-5b178fbe7321.png)

On top of that, the site's font sizes are specified in pixels, which overrides the user's selected default font-size, and the font size is specified at **20 pixels** and the line-height at 1.5.  Using standard lorem ipsum text for testing, that means that only **92 words** can be viewed on each screenful of text.

![ensime2](https://cloud.githubusercontent.com/assets/601365/14214607/9c01f2e6-f803-11e5-9700-63449942c7a6.png)

With some simple adjustments, the situation can be vastly improved.  First, adjusting the margins, padding, and font sizes: All font-size CSS rules were removed, allowing the default browser font-size (in this example, 14pt) to take effect, allowing 441 words to be displayed per screenful:

![ensime3](https://cloud.githubusercontent.com/assets/601365/14214609/9c32e194-f803-11e5-9d13-58195ea9666d.png)

Then the margins and padding were adjusted, allowing 532 words to be displayed per screenful in about 560 pixels of horizontal space, about 58% of the browser window's width:

![ensime4](https://cloud.githubusercontent.com/assets/601365/14214606/9bf80e2a-f803-11e5-861e-4989aab8b6c2.png)

In comparison with the first screenshot of the documentation's `General` section, now much more can be displayed:

![ensime5](https://cloud.githubusercontent.com/assets/601365/14214608/9c182e44-f803-11e5-92b6-638473a2a05c.png)

Then the text justification was removed, increasing the word count to 558 while also making the text easier to read (consistent spacing between words is easier to read, while justified text creates uneven spacing between words, sometimes leaving large gaps between small words):

![ensime6](https://cloud.githubusercontent.com/assets/601365/14214852/f306d5e2-f804-11e5-919c-e2d250f59538.png)

And the `font-size: smaller` rule was removed from `.section-sidebar-nav`, restoring the natural size of the navigation bar text (why make it smaller and harder to read?):

![ensime7](https://cloud.githubusercontent.com/assets/601365/14214853/f30ac5da-f804-11e5-8327-d7fd834456ac.png)

Finally, the `font-size` rule was removed from the `.highlight` class, restoring the size of the code examples.  This results in easy-to-read text and code, and a nice-looking web page:

![ensime8](https://cloud.githubusercontent.com/assets/601365/14214854/f30ca8d2-f804-11e5-9cfb-57e5a30e1695.png)

**Comment by fommil** [comment]
I'm not sure the final product looks particularly nice on a larger monitor, where the spacing is good. If you can put together a PR that works for a wider range of browsers, we will certainly have a look.

**Comment by alphapapa** [comment]
This looks fine to me:

![ensime-wide](https://cloud.githubusercontent.com/assets/601365/14216890/c61de2ee-f810-11e5-932c-ec10956d73a9.png)

Frankly, I'm not an ENSIME user, I'm just a passerby Emacs user who decided to point out a problem and a way to fix it.  I've already spent 15 or 20 minutes altering the CSS and taking all these screenshots to illustrate the problem, so I think I've done my part.  :)  But compare this:

![1](https://cloud.githubusercontent.com/assets/601365/14214605/9b8b3c82-f803-11e5-8952-5b178fbe7321.png)

...to this:

![python](https://cloud.githubusercontent.com/assets/601365/14217018/758811dc-f811-11e5-89c4-e707e25646f5.png)

If you think the first screenshot looks acceptable compared to the Python docs well, hey, it's your project.

**Comment by fommil** [comment]
We know work needs to be done here but we are not CSS experts and I really don't like that condensed version. Most readers have bigger browsers than 1024 width so this may be a corner case.

**Comment by fommil** [comment]
Users with small browsers can swap to the mobile layout, which is vertical rather than horizontal. I'll leave this open to gather interest. If you read the Getting Started page you'll be aware of our approach to tickets ;-) i.e. tickets are for us to help you implement the idea, not the other way round.

**Comment by alphapapa** [comment]
Er...having an editor and documentation side-by-side is a corner case?  I mean...*19%* of the window is used for content.  Can you imagine doing work in that space?

![emacs](https://cloud.githubusercontent.com/assets/601365/14217501/0130e54a-f814-11e5-9773-464e719cacc2.png)

Isn't it more important for it to be usable and readable than to look stylish?

**Comment by fommil** [comment]
Have you tried the mobile layout?

**Comment by alphapapa** [comment]
How would a user do that?

**Comment by fommil** [comment]
Your browser should let you choose the media type. Maybe we could add a button if it's difficult.

**Comment by alphapapa** [comment]
I'm not aware of any option to change the media type in desktop browsers.  The media type is supposed to be selected automatically by mobile browsers, and some of them allow the user to choose to load the full version of the page instead of the mobile one.

Anyway, whatever, it's your project.  I can lead a developer to water...  :)

**Comment by fommil** [comment]
http://stackoverflow.com/questions/3917562/changing-css-media-type-in-browser might help. I've not tied it.

Yeah, you can try leading us to water, but that's not the way it works around here. We'll help **you** implement it, we all have our own priorities and I'm sorry but layout of the website is not even in my top 100. I care about content and I just choose a template that we all liked. Maybe somebody else will be interested and write some adaptive css or javascript. I'll add the design tickets to the Low Hanging Fruit tag on waffle, suitable for new contributors.

**Comment by krux02** [comment]
Ok, I would also like to add my two cents. I work with an 1080p display rotated by 90 degrees ⇒ Same problem but even stronger. It feels very weird, that in the top left, where you find on the majority of the internet the content, on this website it's complete emptyness and the content is squished on the right.

I realized, by zooming in, at some point the website rearranges the content, so that actually everything of the website is used. So the logic is already there, in my opinion, this is just triggered too late. 

I would also suggest to have an intermediate representation, where the two side panels that are currently next to each other, are joined into one single side panel.

**Comment by fommil** [comment]
@krux02 the way it works around here is that PRs are accepted, and we will help you, but nobody's going to do it for you ;-)

**Comment by topisani** [comment]
how about a button that simply hides the menu? that could be done fairly easily, lemme take a look

**Comment by fommil** [comment]
Sounds good!
