### ISSUE TITLE
vim workflow page links to nonexistent emacs workflow page

### ISSUE THREAD

**Issue by ches** [ensime/ensime.github.io#108]
[This page](https://ensime.github.io/editors/vim/workflow/) exists solely to link to an Emacs workflow page, which at this point is gone. I'm not sure what was there, closest thing might be the User Guide?

**Comment by fommil** [comment]
please send a PR with the fix. It is a placeholder until somebody writes it.

**Comment by ches** [comment]
Well, I had hoped for an example of what "workflow" should comprise, if I were to write one…

1. Start the ENSIME server with help of the editor plugin.
2. Do stuff with it… ?
3. Profit!

I'll assume the Emacs User Guide page is the closest thing to a model, then.

**Comment by fommil** [comment]
that's not really a workflow, that's a getting started guide. Workflow is supposed to encompass the understanding of recompiling regularly, etc. Yeah, have a read of the Emacs user guide to get an idea.
