### ISSUE TITLE
Learning Scala Guide

### ISSUE THREAD

**Issue by fommil** [ensime/ensime.github.io#109]
@soc may be interested.

Lots of people are trying out ENSIME without any scala experience.

Having just learnt about 5 new languages, and suffering the pains of getting started as a total n00b, I think it would be really nice of us to have a Learning Scala page with a bunch of TL;DR practicalities to do (installing JDK and sources, installing sbt, setting up a basic project) and a link to learning resources.

It would also be good if we checked that ensime actually supports the popular courses and include practicalities of anything special needed to get it set up.

**Comment by soc** [comment]
@fommil +1. (I'm currently playing with a project in which I deal with setting up/installing/managing OpenJDK and running sbt. This might also help beginners.)

**Comment by idarlington** [comment]
Hi, I am interested in working on this. 

Quick question, does the installation guide have to cover all platforms?

**Comment by fommil** [comment]
Yes it does, but if one already exists then refer to it instead of reinventing the wheel, like we do in the section to install Emacs.

**Comment by fommil** [comment]
@rabbitonweb any chance of your turning your 99 problems repo into a worked practical example? (i.e. about using sbt commands, not about the actual scala content)
