### ISSUE TITLE
gradle / maven features in the grid

### ISSUE THREAD

**Issue by fommil** [ensime/ensime.github.io#112]
on http://ensime.org/build_tools/ can you please add the ticks for gradle / maven? @tanzoniteblack @coacoas or just let me know which features are supported and I'll add them.

**Comment by coacoas** [comment]
For "Upstream License", are you referring to the license of the plugin, or of the build system (e.g, Gradle)?

**Comment by fommil** [comment]
Gradle

**Comment by tanzoniteblack** [comment]
Sorry for the delay, @fommil , been on vacation. Will get to this shortly now that I'm back, once I catch up on the rest of my work.

Questions about it though, maven supports fetching docs and sources on it's own, and if you've already fetched them, the maven plugin for ensime will use them, but it won't fetch them on it's own. Does that still count as a check for you? Or...?

**Comment by fommil** [comment]
yeah, as long as its documented you can add the highly sought-after tick :smile:

**Comment by tanzoniteblack** [comment]
https://github.com/ensime/ensime.github.io/pull/131 will finally update this information this for maven

**Comment by fommil** [comment]
I thought javadoc/source support was just added today? Hours in been there for a while?

**Comment by tanzoniteblack** [comment]
The javadoc bit was new, but we've had source code for a while
