### ISSUE TITLE
"Download" links are well hidden

### ISSUE THREAD

**Issue by Blaisorblade** [ensime/ensime.github.io#120]
Expected behavior: by following obvious links from the Ensime homepage, I figure out how to install it.
Actual behavior: http://ensime.github.io/ leads to http://ensime.github.io/getting_started/, and there you're lost.
Path to improvement: I'm short on time, but I'd consider contributing if there's agreement on what should be there — and if, well, you accept there's an issue.

In fact, Getting Started does not say how to get started at all, which is (if I'm guessing correctly):
- to create a .ensime file, describing your project layout to Ensime, follow instructions appropriate to the build tool you're using.
- to install the Ensime plugin in your editor, follow instructions appropriate to your editor.
- to install the Ensime server, follow instructions X to install https://github.com/ensime/ensime-server... Or not at all? http://ensime.github.io/editors/emacs/install/ seems to suggest this is not needed?
From http://ensime.github.io/contributing/ I can infer this is not needed, apparently, because the Emacs plugin bundles the server...

The third step (or the fact it isn't needed) is not mentioned at all there; the first two are very implicits. A new user is not going to figure out either (except by chance).

In fact, the installation links are hidden in this paragraph about philosophy:

> It is important to realise that ENSIME is not an IDE, it is just one tool in a toolbox, following the UNIX philosophy of Do One Thing and Do It Well.

> - You must be using a build tool that is supported, to generate a .ensime file.
- And you must be using a text editor that is supported, to start and connect to the JVM process.

Moreover, clicking on either link gets to an ambiguous table. To install Ensime there, you need to click on the "Learn more" links.

Instead of offering information, the webpage should call the user to action.

**Comment by fommil** [comment]
thanks for your thoughts. Honestly the only way to improve things is to send a PR, because requests like this will just rot. Looking forward to your PR!

**Comment by fommil** [comment]
btw, you shouldn't need a step 3, the client installs the server automatically.

**Comment by fommil** [comment]
a possibility to improve the grid views is to change the top links around so that the logos are in a row called "Learn More / Install", and the homepages of the editors are on a separate column.

But like the Getting Started says, everybody has their own priorities, so unless you want to do this, it isn't going to get done. We're happy to help if it's not clear how to contribute to the website.

**Comment by fommil** [comment]
Suggested rewording of the "philosophy"

1. You must be using a build tool that is supported, to generate a `.ensime` file describing your project layout. To add support for your build tool, learn about [which build tools we support](...).
2. And you must be using a text editor that is supported, to start and connect to the JVM process. To choose an editor and install the appropriate plugin, learn about [which editors we support](...)

Just so you are aware, I believe that understanding the principles of ENSIME is crucial. I will not merge any PRs to the website that prioritise practicalities over understanding. My personal desire is to prioritise users who read documentation and / or (ideally) contribute back. I have absolutely no personal interest whatsoever in helping users who don't read documentation when asked, aren't interested in how it works, and expect the ensime community to "fix" everything for them. We've had quite a lot of those people pass through and they are time wasters. Those kinds of users think they are customers and they are not (they are welcome to pay me if they want to behave that way).

**Comment by fommil** [comment]
I made the change above on Getting Started, but a PR to the grid pages to make them less ambiguous would be welcome.
