### ISSUE TITLE
Better wording on instructions for SBT.

### ISSUE THREAD

**Issue by frgomes** [ensime/ensime.github.io#146]
In this page http://ensime.github.io/build_tools/sbt/ we can find two paragraphs which are a bit confusing at first glance for newbies.

> Add these lines to ~/.sbt/0.13/plugins/plugins.sbt as opposed to project/plugins.sbt (the decision to use ENSIME is per-user, rather than per-project):

> Check that again, if you incorrectly used ~/.sbt/0.13/plugins.sbt you’ll get an sbt resolution error, it really has to be in the plugins folder.

Whilst the first paragraph is crystal clear for the well initiated, it may eventually cause doubts to newbies. Then we have the second paragraph, which consolidates confusion in case it was not still completely established in the first paragraph. The second paragraph needs a better wording, in order to clarify things.

Suggestion:

> Check that again. You have to add  ``addSbtPlugin`` to ``~/.sbt/0.13/plugins/plugins.sbt`` and not to your ``project/plugins.sbt``, otherwise you’ll get an sbt resolution error. It really has to be in folder ``~/.sbt/0.13/plugins``.

**Comment by fommil** [comment]
could you please raise a PR rather than a ticket?
