### ISSUE TITLE
Need an expanding sidebar

### ISSUE THREAD

**Issue by fommil** [ensime/ensime.github.io#16]
the sidebar and in-page navigation of http://ensime.github.io/ is currently a hack.

It would be nice if a page with subcontent (currently we're calling these `section` layouts) brought out a second vertical sidebar with the list of its subcontent. e.g. the way http://lanyon.getpoole.com/ works, but for subsections. We also have `subpage` layouts, but the distinction between `section` and `subpage` is artificial and just to handle our hack.

(btw our hierarchy is a bit verbose, requiring explicit `section` attributes because the Liquid engine is so limited that it can't do substring matching to automatically detect a hierarchy from a directory structure, and we can't roll custom plugins because we're hosted on gh-pages --- and have no desire to change that.)

**Comment by fommil** [comment]
e.g. http://habilis.net/jah/English.lproj/

**Comment by fommil** [comment]
also relevant http://jekyllrb.com/docs/collections/

**Comment by davegurnell** [comment]
So IIUC, you want an alternate page layout (i.e. make it opt-in) that looks like this:

~~~
+-----+-----+--------------------+
| 1   | 2   | 3                  |
|     |     |                    |
|     |     |                    |
|     |     |                    |
|     |     |                    |
+-----+-----+--------------------+
~~~

Where the numbers are as follows:

1. Main sidebar
2. Page-specific sidebar
3. Page

It'd be easy to add this so you define the sidebar in the YAML front-matter:

~~~
---
title: My page
author: Dave
layout: extra-sidebar
sidebar: |
  <p>This is the extra sidebar.</p>
---

This is the main page content.
~~~

Alternatively, one could potentially write it as a reference to an include file:

~~~
---
title: My page
author: Dave
layout: extra-sidebar
sidebar: my-sidebar.html
---

This is the main page content.
~~~

Would that suffice? The three formats to consider are:

1. HTML text. This is definitely doable
2. Markdown text. Definitely doable with a plugin. May or may not be possible with Github Pages (IIUC they don't support plugins).
3. Link to another file.

**Comment by fommil** [comment]
top diagram is exactly it! Can't we just move our current Navigation div to there? It's somewhat autogenerating... although the impl is a bit hacky (with `section` and `subpage`, but maybe that's ok because we might want them styled differently anyway).

I can't see new `section`s appearing so we shouldn't get too general, although I can imagine people wanting to add more nesting on `subpage`s
