### ISSUE TITLE
On the emacs cheatsheet add commands/function names along with the shortcut

### ISSUE THREAD

**Issue by yyadavalli** [ensime/ensime.github.io#178]
I recently converted from vim to emacs with evil. It took me a while to figure each function to call as I am changing the bindings.

If others think this is a good idea, I can submit the PR.

**Comment by fommil** [comment]
You know about `C-h k`? Might be better to just remind people about this command at the top of the cheatsheet.

**Comment by yyadavalli** [comment]
Yeah, I've been using it a lot. Just thought it would have been easier if the commands are present on the cheatsheet.

**Comment by fommil** [comment]
Is unusual for emacs cheatsheets to do that, so I'm happy doing what is normal.

**Comment by yyadavalli** [comment]
Ok, In that case I'm closing this issue.
