### ISSUE TITLE
More focus on ENJIME

### ISSUE THREAD

**Issue by amanjpro** [ensime/ensime.github.io#210]
Now the `ensime-maven` plugin supports ENSIME 2.0, it also does not depend on `Scala` anymore, and ENJIME is actually a decent Java IDE, should not the website dedicate a page about Java development in ENSIME?

**Comment by fommil** [comment]
I don't see why not, under the Emacs editor section? I tried to be agnostic so maybe try to see what can be changed to make it less scala specific first.
