### ISSUE TITLE
C-c C-d d is listed on the cheat sheet but it is undefined in ensime

### ISSUE THREAD

**Issue by karipahula-avoltus** [ensime/ensime.github.io#236]
The cheat sheet at http://ensime.org/editors/emacs/cheat_sheet/ lists "C-c C-d d	Start the debugger" but trying that (with ensime 1.0.1) just gives an error that the key binding is undefined. Is that key binding supposed to be for `ensime-db-attach`? It doesn't look like there is a binding for that.

**Comment by fommil** [comment]
It'd be best if you sent a PR to ensime-emacs to fix this
