### ISSUE TITLE
Discussion about the LSP-WG note

### ISSUE THREAD

**Issue by gabro** [ensime/ensime.github.io#268]
As suggested by @fommil I'm using this issue to discuss the note published at http://ensime.org/lsp-wg/

I'm done reading everything yet, but I'll post questions as I go:

- "The LSP is truly terrible", it may be, but reading paragraph I'm missing why it is. I would be really interesting if you could elaborate more on this topic, perhaps with a more direct comparison with SWANKY.

- "Unfortunately there are many flavours of LSP" LSP is a defined protocol. It's extensible, yes, but the core is standardized, so I'm not sure I follow your point. What are you referring to with "many flavours"?

- you mention a significant amount of work for integrating clients and languages: AFAIK it's a matter of starting the server from the client, then any generic LSP-client handles the rest. How does this differ from SWANKY (I'm not very familiar with it)?

**Comment by fommil** [comment]
- LSP is terrible. It's very verbose, and uses media transport of basically stdin/stdout. It's also hard to implement anything like a push notification. Compare and contrast this entire package  https://github.com/ensime/ensime-server/tree/3.0/lsp/src/main/scala/org/ensime/lsp to the simple input/output messages that you get in JERKY
- it's such a vague protocol that it ends up being stringly typed and the interpretation to the strings is up for grabs. So you could easily have two scala LSP implementations that are completely incompatible yet 100% LSP complaint. It's not a standard as far as I'm concerned. This also answers your third question.

**Comment by gabro** [comment]
>  It's very verbose, and uses media transport of basically stdin/stdout

Yes, it's more verbose than SWANKY, but how is it a problem?
In [Metals](https://github.com/scalameta/metals/) we've re-implemented (well, mostly @olafurpg did) the LSP Scala bindings from scratch (see the lsp4s subproject) scratch and neither verbosity nor the transport were big problems. Also, we will eventually publish the `lsp4s` library as a standalone library, so any other Scala implementation can just re-use it and deal with a nice Scala API.

>  It's also hard to implement anything like a push notification

What do you mean by that? Servers can send notification to the client, using either one of the core messages (`window/showMessage`/`window/showMessageRequest`/`window/logMessage`) or using a custom notification.

> It's such a vague protocol that it ends up being stringly typed and the interpretation to the strings is up for grabs

I'm very familiar with the protocol, and I disagree. I find it well defined by https://microsoft.github.io/language-server-protocol/specification and very rarely open to doubts in interpretation.

Also, every payload has a detailed TypeScript type, so I don't get the "stringly-typed" argument.

> So you could easily have two scala LSP implementations that are completely incompatible yet 100% LSP complaint. 

LSP is extensible, but if you limit yourself to the official specification, no incompatibility will happen.

The ability to introduce custom messages is a nice feature in case you control servers and clients (e.g. the Java LSP uses a few of them to provide info about indexing), but in general the official specification covers enough cases to be useful and 100% cross-compatibile.

**Comment by fommil** [comment]
my interest in LSP the protocol is about zero, so I'd rather focus on the other parts... I'm basically just saying I want nothing to do with it in the code I maintain :stuck_out_tongue:

**Comment by gabro** [comment]
Hehe ok, as I said on gitter, that was the only point that stoned with my personal opinions (for things on which I have one).

I'd like to stress here the part where you say:

> A shared library that can be used by all language servers would be very useful.

You said this in the context of the Analyser, but I believe it should become a mantra for Scala tooling.

We have very constrained resources and continously embedding solutions of problems into specific tools just won't scale. When working on Metals, we've essentially end up re-implementing a bunch of "boring" stuff found already in Ensime and ScalaIDE because there was no way of sharing code other than copy-pasting it.

I'm thinking of hard problems such as wrapping the presentation compiler beast into a rich API such Ensime does, but also "stupid" problems such as pretty-printing the type-at-point information, or sorting completion members.

In a scale from _no dependencies_ to _Node.js_, I believe we should start leaning towards our JavaScript friends a bit more ;)

Also, big +1 on the need of fixing the presentation compiler. Most of the features it offers are crucial to having a good editor support (think of completions) and the current implementation involves a lot of hacks that I'd rather fix, rather than distribute as a library (although it would be a nice starting point)

So yeah, this is long message to say that I mostly agree with you, including the priorities.

**Comment by olafurpg** [comment]
I agree with @fommil on many points in his post, most importantly

* the bullets under ["scope of a language server"](http://ensime.github.io/lsp-wg/#scope-of-a-language-server), and the presentation compiler only provides a subset of the functionality that's expected to be in a language server
* the hard problem is not the actual wire protocol, the hard problems are the presentation compiller, symbol search, refactoring support, cross-language support, build tool integrations, ...

Just want to my pitch my 2c why I personally like LSP

* the completion API is detailed: https://microsoft.github.io/language-server-protocol/specification#textDocument_completion It supports advanced features like `CompletionItem.additionalTextEdits` and completionItem/resolve to lazily compute expensive data like refactoring patches. This enables features like "autoimport completions" that I take for granted in IntelliJ

![2018-01-11 16 24 45](https://user-images.githubusercontent.com/1408093/37649234-73341af6-2c31-11e8-9a40-7a97f785eead.gif)

* it's a widely adopted standard with support for many languages and editors outside of the scala community. There are features I would like to see added to LSP like semantic highlighting or streaming "find references" but those do not outweigh the tremendous amount of work that we can leverage from non-Scala communities to provide a robust and solid editor experience for the features that matter the most: diagnostics, completions and goto definition.

**Comment by fommil** [comment]
yeah, I think there is room for ensime to continue using the SWANKY / JERKY protocols and for the LSP-WG to build out servers using the LSP, including one with ensime as the backend. That gives us the best of both worlds, and we can try to push common functionality to scalafix / scalameta / build tools / other shared libs as much as possible to minimise duplicated efforts.
