### ISSUE TITLE
jekyll 3.0 in CI

### ISSUE THREAD

**Issue by fommil** [ensime/ensime.github.io#41]
@dwijnand looks like gh-pages just upgraded jekyll, any chance of updating our gem definitions?

https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0

BTW, why do we need so many things listed in the gemfiles, surely there is a meta package that pulls in the gh-pages versions?

**Comment by dwijnand** [comment]
Note that Gemfile is the true source, currently at 4 dependencies, while Gemfile.lock is the derivative. But it's still advisable to commit it apparently.

**Comment by dwijnand** [comment]
Now if only the left hand of github could talk to the right hand: https://pages.github.com/versions/
