### ISSUE TITLE
highres favicon.

### ISSUE THREAD

**Issue by hedefalk** [ensime/ensime.github.io#61]
Super-important! All my browser tabs look great currently except ensime.github.io.

**Comment by fommil** [comment]
hmm, "works for me" (chromium) http://ensime.org/public/favicon.ico

**Comment by hedefalk** [comment]
I get a 16*16 on that url. No work for me.

**Comment by fommil** [comment]
whats lowres to you then? We can do you a 1 pixel one if you'd like? :stuck_out_tongue:

**Comment by hedefalk** [comment]
Oh, sorry. I didn't use imperative in header. It is TOO lowres, looks like
crap on retina :)

**Comment by fommil** [comment]
I think this needs a hipster Mac designer to help out.

**Comment by hedefalk** [comment]
This node script kid might step up to the task. I'm just a tiny bit worried I don't have enough stickers on my MBP to pull it through.
