### ISSUE TITLE
Editor page icons not  consistent size

### ISSUE THREAD

**Issue by chipsenkbeil** [ensime/ensime.github.io#94]
![screenshot_20160317-071823](https://cloud.githubusercontent.com/assets/2481802/13847236/309d5288-ec1a-11e5-9150-0b563248f167.png)
 
Definitely more noticeable when browsing on your phone. This was using Firefox on Android. Had to zoom out really far (or scroll quite a lot) to see the page content.

**Comment by fommil** [comment]
it works for me on my phone and Chromium, can you do a refresh of the page? You might have some stale version of a CSS. The images have a `max-width` element set so your browser is ignoring it.

**Comment by chipsenkbeil** [comment]
Yeah, looks like it was a caching issue. Clearing phone browser cache and refreshing fixed it.
